### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by madebyshape** [engram-design/ImageResizer#1]
I'm having an issue using this add-on when uploading SVG files via assets.

With the ImageResizer add-on disabled / uninstalled the SVG's upload perfectly fine. With it enabled / installed I get this error:

**Upload failed for icon-arrow-right.svg. The error message was: ”Error uploading the file: The file “/.../uploads/icons/icon-arrow-right.svg” does not appear to be an image.“**

But, it seems like the image is uploading because after disabling / uninstalling ImageResizer the images were in fact in the assets to be chosen?!

All folders have the correct permissions and are able to accept that file type. Running Craft Pro 2.4.2693

**Comment by engram-design** [comment]
Ah yes, I don't think we handle SVG's at the moment - they're being treating like images and trying to be resized. It'll still upload as you say, but will fail ungracefully showing you that alert. Will fix asap!

**Comment by engram-design** [comment]
This has been fixed in the [0.0.7](https://github.com/engram-design/ImageResizer/releases/tag/0.0.7) release.

**Comment by madebyshape** [comment]
Brilliant! Thanks for fixing this. Technically it's an image - Just not one that can be manipulated :) Thanks

**Comment by engram-design** [comment]
Not a problem, thanks for raising this issue. Fortunately, there's an `isImageManipulatable` function which makes things a piece of cake :smiley:
