### ISSUE TITLE
Permissions problem?

### ISSUE THREAD

**Issue by paul-frost** [engram-design/ImageResizer#12]
I'm on versions 0.1.3 and 2.6.2793 and if logged in as any user other than Admin if I try and crop an asset I get a message "An unknown error Occured" and no image in the popup. If I log in as Admin it all works fine.
Console log screenshot attached.
![console_log](https://cloud.githubusercontent.com/assets/384378/16450155/6da4af66-3df3-11e6-92b6-09e53ddc02ab.png)
I'm thinking this may be a permissions thing, but can't find anywhere that you can set those for users.

**Comment by engram-design** [comment]
Hey @paul-frost you're absolutely right - all element actions were restricted to Admins. To be honest, I'm not sure why I did that in the first place, but that makes no sense to me! 😆 

In addition, you've raised a good point, where I've now added permissions to you can set it at the User Group level. Check the [0.1.4 release](https://github.com/engram-design/ImageResizer/releases/tag/0.1.4)

**Comment by paul-frost** [comment]
Thanks for the speedy response.
I was a bit concerned using a 0.1 release for a live site, but I think the auto resize on upload is a must for a CMS used by "normal" people, so had to take the risk. But I suspected that it would be safe given your track record.
What do you think you still need to do to make it a 1.0 release?

**Comment by engram-design** [comment]
Not a problem - probably best to not think too much about the version number at this stage. I'll probably bump it up to 1.0 on the next release. The eventual goal is to turn this plugin in a full-featured editor for all manner of things - but thats probably a little further away at this stage, and probably 2.0.
