### ISSUE TITLE
Feature-Reuest: Save Copy of Asset / Non destructive resizing

### ISSUE THREAD

**Issue by maxstrebel** [engram-design/ImageResizer#13]
I'd appreciate if there was an option to make the resize non destructive. If non-destructive is selected, I could imagine that the original image and it's path could be saved in a originals folder and referenced every time when the transform of a certain image is selected.

Last but not least: thank you for the great work on this. I like this plugin because of its simplicity!

**Comment by engram-design** [comment]
We can add that as an option for sure. In most of our use-cases, this is undesirable, as the idea is to reduce the space images take up - but I can certainly see where this might be beneficial. Adding it to the list!

**Comment by maxstrebel** [comment]
Great, thank you!

**Comment by kboduch** [comment]
I vote for this feature +1, but until then I have to find another solution.

**Comment by engram-design** [comment]
This has been added as of the [latest master](https://github.com/engram-design/ImageResizer/archive/master.zip). There are options for non-destructive resizing and non-destructive cropping.

**Comment by Stenvdb** [comment]
@engram-design Is it normal behaviour that the original files aren't saved as Assets entries in the database? I can only access them directly via the file system, they don't show up in the CMS.

**Comment by engram-design** [comment]
Thats correct, they’re not added to Craft as assets - essentially acting like a backup. The reason for this is simple - doing so causes element bloat, meaning you have 2 asset elements for every asset you upload. This would also confuse your content managers, not knowing which asset to pick.

Not to mention, the whole point of this plugin is to reduce file size of images, but I can see the case where non-destructive resizing might be useful.
