### ISSUE TITLE
Ensure Meta data (EXIF) is preserved when resizing images.

### ISSUE THREAD

**Issue by engram-design** [engram-design/ImageResizer#14]

**Comment by paul-frost** [comment]
I've just been bitten by this one and had put in a support request to Craft about it without thinking that this plugin was the problem. It would good to resolve this, as it's quite a big issue with no solution, as you can't rotate images after they have been uploaded.

**Comment by engram-design** [comment]
So sorry for the delay in this, but looking into the issue, it seems like Craft's native `$image->saveAs` method strips out EXIF data. Image Resizer relies on this function pretty heavily, and its something I would expect to be handled by default - but thats how it goes.

In any case, I've come to a solution of my own using Craft already included `PelJpeg` library, which can handle this better.

Check out the [latest master](https://github.com/engram-design/ImageResizer/archive/master.zip).
