### ISSUE TITLE
Feature request: Make all strings translatable

### ISSUE THREAD

**Issue by lboaretto** [engram-design/ImageResizer#15]
Hello,

I tried this, for example:

`Craft.t('You are about to resize {actionDescription} to be a maximum of {settings_width}px wide and {settings_height}px high. Alternatively, set the width and height limits below for on-demand resizing.', { actionDescription: actionDescription, settings_width: settings.width, settings_height: settings.height})` on ResizeElementAction.js

And other simple strings ... but I don't know why does not translate. Could it be by calling JS on ElementAction? Loading js files is done on demand (after click on Resize image).

**Comment by engram-design** [comment]
You're totally correct on this one, with JS, you need to essentially prepare Craft to utalize those certain strings for translation. Added as of the [latest master](https://github.com/engram-design/ImageResizer/archive/master.zip).
