### ISSUE TITLE
If resized image is larger filesize than original image, resize should skip.

### ISSUE THREAD

**Issue by pixeljitsu** [engram-design/ImageResizer#2]
Love this plugin, awesome work! You've really helped me reduce bandwidth and traffic coming from Craft image assets. I've seen real world savings of 500+ MB where clients were uploading 5 MB images that when resized down to the the correct resolution limits were only 90 KB.

Just one thing FYI though:

I've a few PNG+a images that are 1000x1000px @ ~110-140 KB each.  Resizing them to 960x960px @ 80% quality, yields images ~350-370 KB each. Here are few for you to test:

If the resized image is actually larger in file size than the original image, perhaps there should be a setting to skip the de-optimizations if they occur.

Thanks :)

Don't know if GH will recompress these in this post or not.

![a](https://cloud.githubusercontent.com/assets/2178979/10962202/55d20b8a-8364-11e5-93d9-2ffacd4e260b.png)
![b](https://cloud.githubusercontent.com/assets/2178979/10962200/55cfca3c-8364-11e5-9502-0cb5ffcba5d6.png)
![c](https://cloud.githubusercontent.com/assets/2178979/10962201/55d020f4-8364-11e5-91bc-7d955d5ccf1a.png)

**Comment by pixeljitsu** [comment]
Also, will quality adjustments apply to smaller than limit images.  Say that my max size is 1000 x 1000 @ 80% quality.  Will a 500 x 500 image currently saved @ 100% quality be resaved at 80% even though it is smaller than the max px dimensions?

**Comment by engram-design** [comment]
A very good point, I'll look at adding that soon. In your example, the image wouldn't get resized, because its less than the dimensions you've specified. If you don't specify an image quality value, it will use Craft's default image compression value.

**Comment by engram-design** [comment]
Added in [0.1.3](https://github.com/engram-design/ImageResizer/releases/tag/0.1.3) with just some basic support for this. Assets unable to be converted due to a larger resulting filesize will be ignored. There's also a plugin setting for this which is default to on, but you can switch off if you really want larger files 😃
