### ISSUE TITLE
On bulk resize error: stoptrackingtaskprogress

### ISSUE THREAD

**Issue by thomasvankerckvoorde** [engram-design/ImageResizer#20]
On bulk resize I get a Javascript error and the progress bar is stuck.

    stoptrackingtaskprogress is not a function

Resizing does work when I check filesizes.

![screen shot 2017-03-10 at 11 30 52](https://cloud.githubusercontent.com/assets/2323270/23791905/1f2546d4-0585-11e7-8df9-67c79aa5d95d.png)
![screen shot 2017-03-10 at 11 30 43](https://cloud.githubusercontent.com/assets/2323270/23791906/1f25a87c-0585-11e7-8bb9-7c811176186d.png)

**Comment by darylknight** [comment]
I get this too - it seems to stop the images from resizing at all

**Comment by darylknight** [comment]
However, if I implement the pull request related to this issue, it fixes the javascript error, but the image resize still doesn't work.

**Comment by engram-design** [comment]
Thanks for your patience guys - this was caused by [Craft 2.6.2962](https://craftcms.com/changelog#2-6-2962) with its changes to how tasks are run, and a few builds back (I don't know which specific one). Errors should be gone now.

@darylknight I've tested for single and bulk resizing, and is working as expected with this fix. Can you check your logs `imageresizer.log` to see if there are any memory warnings? This can happen if the image to resize is too large...

**Comment by darylknight** [comment]
Hi Josh,

I've just tested this and still doesn't seem to be working. Latest version of the plugin, Craft 2.6.2967. When I try to resize an image already on the server, it says it's resized it successfully, but the image dimensions don't change. There's also nothing in the log when I try to do that. PHP memory limit was upped to 1GB but it didn't change anything.

I downloaded a large image (2772 x 3174) and resaved it in Photoshop to eliminate the possibility of client error, then re-uploaded it to the site. It appeared in my assets folder unmodified, but this time I've got this in `imageresizer.log`:

    2017/03/24 11:34:39 [info] [plugin] [Forced] Did not resize assets58d5044d504688.29135318.jpg as it would result in a larger file.
    in /srv/users/serverpilot/apps/appname/craft/app/etc/plugins/BasePlugin.php (65)
    in /srv/users/serverpilot/apps/appname/craft/plugins/imageresizer/services/ImageResizer_ResizeService.php (55)
    in /srv/users/serverpilot/apps/appname/craft/plugins/imageresizer/ImageResizerPlugin.php (188)

    ******************************************************************************************************

Thanks!
Daryl

**Comment by darylknight** [comment]
Issue resolved - this is actually working, but the image I ran it on would have been larger than the original file if it had resized it, so the plugin didn't transform the image.
