### ISSUE TITLE
Log Clearing now working

### ISSUE THREAD

**Issue by bgarrant** [engram-design/ImageResizer#26]
When I go to clear the log with the new version I get this error.

"Craft\ImageResizer_LogsController._currentLogFileName" is not defined.

**Comment by engram-design** [comment]
Fixed in the [latest master](https://github.com/engram-design/ImageResizer/archive/master.zip).

**Comment by bgarrant** [comment]
Works great Josh.  Thanks.

 

Bryan Garrant

Garrant Consulting LLC

518.327.5159
