### ISSUE TITLE
Resize on upload cant be turned off

### ISSUE THREAD

**Issue by KoenRijpstra** [engram-design/ImageResizer#35]
### Description
If I disable `Resize on upload` the setting doesn't get saved:
![image](https://user-images.githubusercontent.com/579455/35444442-dd6eea4c-02ae-11e8-9d47-9354e819b128.png)

### Steps to reproduce

1. Go to the settings page
2. Turn of `Resize on upload` on a specific asset resource
3. press Save

### Additional info

- Plugin version: 1.0.1
- Craft version: 2.6.3002

**Comment by engram-design** [comment]
The latest [1.1.0 release](https://github.com/verbb/image-resizer/releases/tag/1.1.0) fixed this.
