### ISSUE TITLE
Images won't upload (on some particular client devices)

### ISSUE THREAD

**Issue by jnaklaas** [engram-design/ImageResizer#36]
### Description
This is a very weird bug and I can't wrap my head around it. I installed the plugin on a live website and everything works as expected. I can resize/compress images that were previously uploaded and new images get resized automatically. It works, ON MY DEVICE. My client who is also the content manager, for some reason can't.

Whenever he uploads an image, it shows the loading bar animation, and after that an infinitely spinning wheel. The images do get stored in the storage>runtime>temp, but not in the assets folder. 
This is also the case in the bug described in issue  #33. As it's suggested there to be solved by moving the site to a different server, I'm not sure if that issue is related to mine.

Obviously, the client and I are working on the same (live) website, so I'm assuming it's nothing to do with my server settings, since everything works as expected here.
We both have the same internet provider. I tested the plugin on my mac on his home network, and it still works for me.
I'm on Mac OSX, my client is on a Windows. All my browsers here do the trick, all his browsers don't (tested in Internet Explorer, Edge and Google Chrome).

Disabling the image-resizer plugin gives no issues when uploading images.

### Steps to reproduce

1. Upload one or more images via the File Manager or content>entry in the craft backend.
2. Endless spinning wheel.
3. Image stays inside : storage>runtime>temp.

### Additional info

- Plugin version: 1.1.0
- Craft version: 2.6.3005

**Comment by engram-design** [comment]
Closing - the Craft 2 version is no longer supported.
