### ISSUE TITLE
Error. Not enough memory available to perform this image operation.

### ISSUE THREAD

**Issue by terryupton** [engram-design/ImageResizer#37]
### Description
Trying to resize a large image to 2000px wide. But keep hitting this error.
Error. Not enough memory available to perform this image operation.

### Steps to reproduce

1. Click the image and then choose resize
2. Or use the resize batch in the image resize panel

### Additional info
I have ramped up my PHP memory limit to a whopping 5500M. 

- Plugin version: 1.1.0
- Craft version:  2.6.3000

**Comment by terryupton** [comment]
******************************************************************************************************
2018/02/15 17:51:57 [info] [plugin] [Forced] {"taskId":"899mg","handle":"error","filename":"UAV-Vogel-Orthophoto-Guildford.jpg","data":{"message":"Not enough memory available to perform this image operation."}}
in /home/vagrant/sites/Plowman Craven V4/plowmancraven.co.uk/craft/app/etc/plugins/BasePlugin.php (65)
in /home/vagrant/sites/Plowman Craven V4/plowmancraven.co.uk/craft/plugins/imageresizer/services/ImageResizer_LogsService.php (24)
in /home/vagrant/sites/Plowman Craven V4/plowmancraven.co.uk/craft/plugins/imageresizer/services/ImageResizer_ResizeService.php (151)

******************************************************************************************************

**Comment by terryupton** [comment]
I should add this only applies to images that already exist on the system. New images (even much larger) are resized perfectly fine.

**Comment by engram-design** [comment]
Interesting to hear its only for existing images. Have you tried modifying the Craft [phpMaxMemoryLimit](https://craftcms.com/docs/config-settings#phpMaxMemoryLimit) setting?

This also sounds like its on a local site, have you tried from a staging server?

**Comment by terryupton** [comment]
Hi @engram-design - you are right it was the Craft phpMaxMemoryLimit setting. I updated this and it worked both locally (homestead) and on the staging server too.

**Comment by engram-design** [comment]
Great to hear! Closing this one for now.
