### ISSUE TITLE
Image Resizer causes scripts to fail loading

### ISSUE THREAD

**Issue by mimamuh** [engram-design/ImageResizer#38]
### Description
After installing image-resizer I can't change uploaded filenames and their alt attribute in the "assets" section any longer. The save-script fails with:
````
jquery.js:9566 POST https://craft-3-transform-bug.test/index.php?p=admin/actions/elements/save-element 500 (Internal Server Error)
``` 

When I deactivate `image-resizer` it works again.

### Steps to reproduce

1. install `image-resizer`
2. change a file-name in "assets"
3. try to save changes and it should fail (hopefully :))

### Additional info

- Plugin version: 2.0.1
- Craft version: 3.0.0-RC10.1

**Comment by engram-design** [comment]
This should be fixed in the latest commit, try doing a `composer require verbb/image-resizer:dev-craft-3`, but will be rolled into the next release.
