### ISSUE TITLE
Error when opening an image modal and clicking save

### ISSUE THREAD

**Issue by richhayler** [engram-design/ImageResizer#39]
### Description
When double clicking on an image asset (within an entry edit page) and then clicking on “save” within the image asset modal an error occurs and any changes to the image fields are not saved. 

Here is the error displayed in the log:

`[error][TypeError] TypeError: Argument 3 passed to verbb\imageresizer\services\Resize::resize() must be of the type string, null given, called in /apps/crafty/vendor/verbb/image-resizer/src/ImageResizer.php on line 98 and defined in /apps/crafty/vendor/verbb/image-resizer/src/services/Resize.php:31`

### Steps to reproduce

1. Add an image asset field (with default image resize settings applied) to an entry section
2. Create a new entry in the section
3. Click on the image asset field and select or upload a new image
4. Double click on the “green circle icon” next to the image to bring up the image modal
5. Click save in the modal window

### Additional info

- Plugin version: 2.0.1
- Craft version: rc11

**Comment by dhmax88** [comment]
Having the same issue here.

**Comment by engram-design** [comment]
This should be fixed in the latest commit, try doing a `composer require verbb/image-resizer:dev-craft-3`, but will be rolled into the next release. Also reported in #38.
