### ISSUE TITLE
Images hosted in Rackspace Cloud Files

### ISSUE THREAD

**Issue by dave-agilepixel** [engram-design/ImageResizer#4]
I'm trying your plugin on Craft 2.5, I've installed it and the plugin appears to work, when I upload a file I can click the tick, choose "crop" and then apply a crop however whenever I try to "save" the cropped file I get the error in red at the top centre that the crop failed.  I presume this is because the files are held on Rackspace Cloud Files and there's some issue with editing them in this location?  

Would be great to know if this is a known issue and if there's a likely resolution in the pipeline.

Thanks for your help.

**Comment by engram-design** [comment]
While I haven't investigated it fully yet, I certainly plan to support non-local asset sources like Rackspace and AWS if at all possible. I'll add it to the roadmap, and also add some notes on the plugin page.

**Comment by dave-agilepixel** [comment]
That's great news thanks for the update, I'll keep an eye out

**Comment by engram-design** [comment]
Image Resizer now supports all asset sources - local and remote as of [version 0.1.2](https://github.com/engram-design/ImageResizer/releases/tag/0.1.2).
