### ISSUE TITLE
"Resize for remote sources not supported"

### ISSUE THREAD

**Issue by jamiewade** [engram-design/ImageResizer#40]
### Description
When uploading assets (and resizing existing assets), I get the error:

> Resize for remote sources not supported.

This is concerning assets in an AmazonS3 bucket. Note that the bucket is fully configured and works with the site. Normal Craft transforms etc work perfectly.

### Steps to reproduce

1. Install and enable plugin
2. Either:
    a) Upload a new asset (AmazonS3)
    b) Resize an existing asset (AmazonS3)

### Additional info

- Plugin version: 1.1.0
- Craft version: 2.6.3011

Screenshot with the error logs:

![screenshot-01](https://user-images.githubusercontent.com/6672331/36683307-297ce5fa-1b15-11e8-9b1a-23fd51a0be37.jpg)

Screenshot with plugin settings:

![screenshot-02](https://user-images.githubusercontent.com/6672331/36683326-3140629e-1b15-11e8-82f6-43e4aef8c3e4.jpg)

_Thanks for taking the time to build this plugin. It is exactly what we were looking for, and I hope we can resolve this issue._

**Comment by jamiewade** [comment]
I've just seen that resizing from remote sources isn't supported in Craft 2.x:

> [Added] Skip resizing of remote assets because their are tricky to handle in craft 2.

https://github.com/verbb/image-resizer/releases/tag/1.1.0

😢

**Comment by engram-design** [comment]
Closing - the Craft 2 version is no longer supported.
