### ISSUE TITLE
Error opening log

### ISSUE THREAD

**Issue by Coysh** [engram-design/ImageResizer#42]
### Description
When clicking on 'Log' I get the following error:

`count(): Parameter must be an array or an object that implements Countable`

Stack trace:
yii\base\ErrorException: count(): Parameter must be an array or an object that implements Countable in /home/vagrant/sites/craft/vendor/verbb/image-resizer/src/services/Logs.php:100
Stack trace:
#0 /home/vagrant/sites/craft/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(2, 'count(): Parame...', '/home/vagrant/s...', 100)
#1 /home/vagrant/sites/craft/vendor/verbb/image-resizer/src/services/Logs.php(100): craft\web\ErrorHandler->handleError(2, 'count(): Parame...', '/home/vagrant/s...', 100, Array)
#2 /home/vagrant/sites/craft/vendor/verbb/image-resizer/src/controllers/LogsController.php(16): verbb\imageresizer\services\Logs->getLogEntries()
#3 [internal function]: verbb\imageresizer\controllers\LogsController->actionLogs()
#4 /home/vagrant/sites/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /home/vagrant/sites/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /home/vagrant/sites/craft/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('logs', Array)
#7 /home/vagrant/sites/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('logs', Array)
#8 /home/vagrant/sites/craft/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('image-resizer/l...', Array)
#9 /home/vagrant/sites/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('image-resizer/l...', Array)
#10 /home/vagrant/sites/craft/vendor/craftcms/cms/src/web/Application.php(226): yii\web\Application->handleRequest(Object(craft\web\Request))
#11 /home/vagrant/sites/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /home/vagrant/sites/craft/public/index.php(17): yii\base\Application->run()
#13 {main}

### Steps to reproduce

1. Go to Settings for plugin
2. Click 'Log'

### Additional info

- Plugin version: latest
- Craft version: 3 RC15

**Comment by smcyr** [comment]
Same for me, I think it's because of PHP 7.2

**Comment by engram-design** [comment]
Fixed in [2.0.3](https://github.com/verbb/image-resizer/releases/tag/2.0.3).
