### ISSUE TITLE
Asset Error: _resizeImage() must be of the type integer or null, string given.

### ISSUE THREAD

**Issue by whoisjuan** [engram-design/ImageResizer#44]
### Description

When loading an asset via FeedMe from a URL, I get this error in the FeedMe logs:

> Asset error: https://waveguide-screenshots-optimized.s3.us-west-2.amazonaws.com/mobile/Bobby2-iPhoneX/Bobby2-iPhoneX_nca2b.JPG - Argument 3 passed to verbb\imageresizer\services\Resize::_resizeImage() must be of the type integer or null, string given, called in /srv/app/artifact/htdocs/vendor/verbb/image-resizer/src/services/Resize.php on line 98

Found this issue while troubleshooting another issue I have with Feed Me. 
This (for reference) -> https://github.com/verbb/feed-me/issues/305

### Additional info

- Plugin version: 2.0.2
- Craft version: 3.0.4

**Comment by richhayler** [comment]
I get similar error when using a global variable, e.g {slug} in the asset field upload path to create a dynamic sub folder in the volume. 

Upload failed. The error message was: “Argument 1 passed to verbb\imageresizer\services\Service::getSettingForAssetSource() must be of the type integer, null given, called in ...apps/craft/vendor/verbb/image-resizer/src/ImageResizer.php on line 95”

**Comment by engram-design** [comment]
Fixed in [2.0.3](https://github.com/verbb/image-resizer/releases/tag/2.0.3).
