### ISSUE TITLE
Images failing to upload from an asset source with a matrix field.

### ISSUE THREAD

**Issue by marcushouse** [engram-design/ImageResizer#45]
### Description
When uploading an image to an asset source with a dynamic folder based on the {owner.slug} , I'm getting the following error.

"Upload failed. The error message was: “Argument 1 passed to verbb\imageresizer\services\Service::getSettingForAssetSource() must be of the type integer, null given, called in ###PATH###/vendor/verbb/image-resizer/src/ImageResizer.php on line 95”"

It seems to be failing to create the dynamic volume folder prior to attempting the resize.
If that dynamic folder already exists, it does not throw the error.

### Steps to reproduce

1. Create a matrix with an asset field.
2. Select "Restrict uploads to a single folder?" and restrict to a volume with {owner.slug} specified.
3. Try using the matrix field to upload a new image (The volume folder matching the {owner.slug} should not exist first) 
4. You should get a browser alert with the above error.

### Additional info

- Plugin version: 2.0.2
- Craft version: 3.0.4

**Comment by theurbanu** [comment]
I got the same exact error above. Same situation and environment.

**Comment by DennisWemyss** [comment]
Same with Craft version: 3.0.5

**Comment by engram-design** [comment]
Fixed in [2.0.3](https://github.com/verbb/image-resizer/releases/tag/2.0.3).
