### ISSUE TITLE
"A file with the name image_name.jpg already exists" warning for all images

### ISSUE THREAD

**Issue by frankharrison-wj** [engram-design/ImageResizer#46]
### Description

When uploading an image large enough to trigger Image Resizer, Craft warns `A file with the name “image_name.jpg” already exists.` even when it's a new image with a unique filename. We're using Amazon S3, and I wonder whether Craft first uploads the full-size image, then Image Resizer uploads it's version and thinks there's a conflict? I've tried updating asset indexes but this doesn't fix the issue.

### Steps to reproduce

1. Upload an image to an Amazon S3 volume that has Image Resizer activated

### Additional info

- Plugin version: 2.0.3
- Craft version: 3.0.25

**Comment by engram-design** [comment]
Does it throw this error for any file you try to upload, or just some? I'll need to crack out S3 to do some testing, but not seen that yet.

**Comment by frankharrison-wj** [comment]
It happens for any image that's large enough for Image Resizer to kick in. If it's below the dimensions in Image Resizer's settings it uploads fine. Let me know if you need anything else to diagnose.

**Comment by engram-design** [comment]
Fixed in [2.0.4](https://github.com/verbb/image-resizer/releases/tag/2.0.4)

**Comment by frankharrison-wj** [comment]
Awesome, thank you
