### ISSUE TITLE
"Image already under the maximum width/height" when it's not

### ISSUE THREAD

**Issue by jayhlee** [engram-design/ImageResizer#49]
### Description
When I try to resize a large image (4096x2733, 1.4MB) by Bulk Resize to a max image width/height of 2048, my logs show that the image resize was skipped because "Image already under the maximum width/height." I tried setting the width to 2048 and height to 0 as well, but it still skips. 

Any idea why it's skipping?

### Steps to reproduce

1. In Imager Resizer Settings > Bulk Resize, select Bulk Resize for an Asset folder that includes large image (4096x2733).
2. In modal with resize options, set width and height to 2048 (or height to 0).

### Additional info

- Plugin version: 2.0.4
- Craft version: 3.0.34

**Comment by engram-design** [comment]
Can't seem to replicate this on my end. Would you be able to share your volume settings? Wondering if you have images set to resize on upload, and what any defaults are?

Have you also tried resizing it from the element action (go to Assets, select the file, and select Resize on the cog icon button)?

Maybe even try re-indexing assets in that volume?

**Comment by jayhlee** [comment]
Here's my volume settings, which are based on nystudio107's Craft 3 Multi-Environment setup.

```
<?php
return [

    // All environments
    '*' => [
        'ASSET_HANDLE' => [
            'path' => '@basePath/ASSET_PATH',
            'url' => '@baseUrl/ASSET_PATH',
        ],
    ],

    // Live (production) environment
    'live'  => [
    ],

    // Staging (pre-production) environment
    'staging'  => [
    ],

    // Local (development) environment
    'local'  => [
    ],
];
```

I did some more experimenting and it seems like I have issues with some images while other images seem to work fine. For the images that don't work, I also tried to resize from the element action and tried re-indexing the assets in the volume. But both attempts didn't work.

I've uploaded a video to demonstrate this. In the video, the first image works. However, the second image doesn't resize. 
[https://drive.google.com/file/d/1NK8Qp1oxn7RJoyKlb9d_Dl1d_0-xXBg8/view?usp=sharing](url)

**Comment by joshuabaker** [comment]
I’m experiencing this too. At a glance, it seems like the plugin overwrites the width and height but fails to resize the image (therefore skipping on a second run).

The test [image](https://unsplash.com/photos/z0bACVUDTJM) I’m using is from Unsplash. Volume is S3.

**Comment by joshuabaker** [comment]
Whilst logging throughout the flow and forcing a resize, there seems to be an issue even with the original width and height.

<table>
  <tr>
    <td>After updating asset indexes (via Assets interface)</td>
    <td>5760&nbsp;×&nbsp;3840&nbsp;px</td>
  </tr>
  <tr>
    <td>Logging <code>$image->getWidth()</code> and <code>$image->getHeight()</code> at the start of <code>Resize::_resizeImage</code></td>
    <td>2000&nbsp;×&nbsp;1333&nbsp;px</td>
  </tr>
  <tr>
    <td>Logging <code>$dimensions[0]</code> and <code>$dimensions[1]</code> inside <code>Resize::_resizeImage</code></td>
    <td>2048&nbsp;×&nbsp;1365&nbsp;px</td>
  </tr>
</table>

I’m wondering if this might be an issue with a dependency (i.e. Craft, Imagine, GD)?

**Comment by joshuabaker** [comment]
@engram-design Do you have any thoughts on this?

**Comment by engram-design** [comment]
Might be worth trying [2.0.6](https://github.com/verbb/image-resizer/releases/tag/2.0.6)

**Comment by joshuabaker** [comment]
@engram-design Thanks, Josh. We’ll give that a shot and report back.

**Comment by engram-design** [comment]
Closing for now, but hit me up if its still an issue. My testing at least seems to be playing the game.
