### ISSUE TITLE
"Skipped non image" when uploading image from front-end form

### ISSUE THREAD

**Issue by hannahwoodward** [engram-design/ImageResizer#50]
### Description
When uploading an image via a front-end form, Image Resizer skips over images with the reason "skipped non image". I had a look into the where the logging comes from, and it looks like it's failing on this line:
https://github.com/verbb/image-resizer/blob/e08a08ee66feafeb03b16e9b3bbddbf6fd54041b/src/services/Resize.php#L43

From a front end upload, the value of `@pathinfo($path, PATHINFO_EXTENSION)` is an empty string, and the value of `$path` is `'/tmp/phpBdbLIe'`. Comparatively, uploading the same image through the CMS gives the value of `@pathinfo($path, PATHINFO_EXTENSION)` is `EXT01_HK.jpg` and the value of `$path` is `/sites/site-name/storage/runtime/temp/EXT01_HK5cb839db1cd847.86416297.jpg`

The image is still successfully uploaded in either instance, but Image Resizer will skip over processing the image from the front-end (but not when uploading via Craft).

### Steps to reproduce

1. Create a form on the front-end of a Craft build with an file type input
2. Upload an image through form

### Additional info

- Plugin version: 2.0.4
- Craft version: 3.1.23

**Comment by engram-design** [comment]
Strange, not seeing this on my end, as `$path` equals to `path/storage/runtime/temp/assets5d821d5164a769.81524718.png`, similar to how it is in the control panel.

I'll keep testing.

**Comment by engram-design** [comment]
Might be worth trying [2.0.6](https://github.com/verbb/image-resizer/releases/tag/2.0.6) as well.

**Comment by hannahwoodward** [comment]
Passing this on to @charliegrinsted & @samjoneill

**Comment by engram-design** [comment]
Closing for now, but feel free to open if there are more issues.
