### ISSUE TITLE
Depreciation Warning Craft 3

### ISSUE THREAD

**Issue by moondawg69** [engram-design/ImageResizer#51]
### Description

craft\helpers\FileHelper::removeFile() is deprecated. Use craft\helpers\FileHelper::unlink() instead.

vendor/verbb/image-resizer/src/services/Logs.php

### Steps to reproduce

1. Run the clear logs function in the plugin
2. View Craft's Depreciation Warnings

### Additional info

- Plugin version: 2.0.4
- Craft version: 3.1.28

**Comment by engram-design** [comment]
Fixed in [2.0.5](https://github.com/verbb/image-resizer/releases/tag/2.0.5)
