### ISSUE TITLE
The createDir() method has been deprecated

### ISSUE THREAD

**Issue by thupsi** [engram-design/ImageResizer#58]
When I set the option to keep original images there is a deprecation warning in the CP:
"The createDir() method has been deprecated. Use createDirectory() instead."

![image](https://user-images.githubusercontent.com/19857599/108191480-d6fea380-711b-11eb-9d06-7edb16d61e7e.png)

**Steps to reproduce**
1. Enable the "Non-destructive" setting
2. Do some resizing with the plugin

**Additional info**
- Plugin version: 2.0.10
- Craft version: Craft Pro 3.6.6
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/image-resizer/releases/tag/2.1.0)
