### ISSUE TITLE
Class "verbb\imageresizer\services\ImageHelper" not found when saving user image in Front-End form

### ISSUE THREAD

**Issue by nicolaskrebs** [engram-design/ImageResizer#64]
### Describe the bug

**Class "verbb\imageresizer\services\ImageHelper" not found when saving user image in Front-End form**

There seems to be a Class missing (verbb\imageresizer\services\ImageHelper) in the file `src/services/Service.php`, throwing an error in the `saveAs()` function. This only happens when trying to save a new image in a Front-End User Profile Form.

        switch ($orientation) {
            case ImageHelper::EXIF_IFD0_ROTATE_180:
                $degrees = 180;
                break;
            case ImageHelper::EXIF_IFD0_ROTATE_90:
                $degrees = 90;
                break;
            case ImageHelper::EXIF_IFD0_ROTATE_270:
                $degrees = 270;
                break;
        }

If I comment out the switch case, everything seems to work fine.

### Steps to reproduce

1. Create a Front-End profile edit form
2. Activate resizing for the user profile picture volume in the Control Panel
3. Save a new profile picture in the Front-End

### Craft CMS version

4.1.4.1

### Plugin version

3.0.0

### Multi-site?

No

**Comment by nicolaskrebs** [comment]
Created a pull request: #65

**Comment by engram-design** [comment]
Oops, missed this one, thanks!
