### ISSUE TITLE
Bulk  and batch resizing fails with queue error

### ISSUE THREAD

**Issue by alexroper** [engram-design/ImageResizer#68]
### Describe the bug

When trying to bulk resize image in a asset source or batch resize images from the Assets listing page, the confirmation modal stalls out. When I check the queue I see the job has failed with this error:

> Cannot assign int to property craft\elements\Asset::$dateModified of type ?DateTime

Here's the job data, if that helps:

```json
{
    "description": "Resizing images",
    "taskId": "VDodS",
    "assetIds": [
        2633,
        2616,
        2615,
        2614,
        2613,
        2612,
        2611,
        2609,
        2610,
        1456,
        1398,
        1397,
        1372,
        1299,
        27
    ],
    "imageWidth": 2100,
    "imageHeight": 2100
}
```

PHP 8.1.6
Craft 4.2.4
Image Resizer 3.0.1

### Steps to reproduce

1. Go to Image Resizer > Settings > Resize Bulk
2. Click the "Bulk resize" button next to an asset source
3. Click the "Resize" button in the modal window that opens
4. Close the window and go to Utilities > Queue Manager
5. Find the failed job

### Craft CMS version

4.2.4

### Plugin version

3.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed in [3.0.2](https://github.com/verbb/image-resizer/releases/tag/3.0.2)
