### ISSUE TITLE
Resizing fails on initial image upload

### ISSUE THREAD

**Issue by mattslack** [engram-design/ImageResizer#69]
### Describe the bug

When attempting to upload a new image it fails with an error about a missing argument.
<img width="454" alt="image" src="https://user-images.githubusercontent.com/274/200397816-830f7e57-c532-465f-a5e9-f61fb884c9c4.png">

If you retry the same image it will work the second time, but will fail again as soon as you try a different image.

It looks like the `sessionID` is required by [craft's AssetIndexer](https://github.com/craftcms/cms/blob/4d31ee3472fa0e53b06480c2e79826117a96786f/src/services/AssetIndexer.php#L498), but image-resizer does not pass it.

Note: previous to upgrading to image-resizer 3.0.3 I received a similar error, which makes me think the fix in https://github.com/verbb/image-resizer/commit/92a0b400615c692cb538ea2c1f221aaab8139f04 was incomplete.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/274/200399067-3500ce83-7d69-4aed-bbaa-dfd88f8e1167.png">

### Steps to reproduce

1. Edit an entry with an asset field in it
2. Attempt to upload a new image that is resizable and does not already exist as an asset
3. Observe the error for a missing argument.

### Craft CMS version

Craft Pro 4.3.1

### Plugin version

3.0.3

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed in [3.0.4](https://github.com/verbb/image-resizer/releases/tag/3.0.4)
