### ISSUE TITLE
Allow resizing action to be performed on selected folder

### ISSUE THREAD

**Issue by engram-design** [engram-design/ImageResizer#7]
Duplicating whats currently possible with element actions - accept automatically doing so for a chosen folder. Particularly handy for large folders. @mmikkel

**Comment by engram-design** [comment]
Added in [0.1.3](https://github.com/engram-design/ImageResizer/releases/tag/0.1.3).

**Comment by mmikkel** [comment]
Awesome, @engram-design – thanks!
