### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by krisMoca** [engram-design/ImageResizer#73]
### Describe the bug

Hi Guys,

I've tried different versions (3.0.x) and still getting "A server error occured". Managed to get retrieve from the log and here's the error.

[web.ERROR] [yii\base\ErrorException:2] Undefined array key "enabled" {"trace":["#0 /container/application/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\\base\\ErrorHandler->handleError(2, 'Undefined array...', '/container/appl...', 67)","#1 /container/application/vendor/verbb/image-resizer/src/services/Service.php(67): craft\\web\\ErrorHandler->handleError(2, 'Undefined array...', '/container/appl...', 67)","#2 /container/application/vendor/verbb/image-resizer/src/services/Service.php(44): verbb\\imageresizer\\services\\Service->getSettingForAssetSource(2, 'enabled')","#3 [internal function]: verbb\\imageresizer\\services\\Service->beforeHandleAssetFile(Object(craft\\events\\AssetEvent))","#4 /container/application/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\\events\\AssetEvent))","#5 /container/application/vendor/yiisoft/yii2/base/Component.php(642): yii\\base\\Event::trigger('craft\\\\elements\\\\...', 'beforeHandleFil...', Object(craft\\events\\AssetEvent))","#6 /container/application/vendor/craftcms/cms/src/elements/Asset.php(2733): yii\\base\\Component->trigger('beforeHandleFil...', Object(craft\\events\\AssetEvent))","#7 /container/application/vendor/craftcms/cms/src/services/Elements.php(2931): craft\\elements\\Asset->beforeSave(true)","#8 /container/application/vendor/craftcms/cms/src/services/Elements.php(1063): craft\\services\\Elements->_saveElementInternal(Object(craft\\elements\\Asset), true, true, NULL, NULL, false)","#9 /container/application/vendor/craftcms/cms/src/controllers/AssetsController.php(312): craft\\services\\Elements->saveElement(Object(craft\\elements\\Asset))","#10 [internal function]: craft\\controllers\\AssetsController->actionUpload()","#11 /container/application/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)","#12 /container/application/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)","#13 /container/application/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction('upload', Array)","#14 /container/application/vendor/craftcms/cms/src/web/Application.php(302): yii\\base\\Module->runAction('assets/upload', Array)","#15 /container/application/vendor/craftcms/cms/src/web/Application.php(627): craft\\web\\Application->runAction('assets/upload', Array)","#16 /container/application/vendor/craftcms/cms/src/web/Application.php(281): craft\\web\\Application->_processActionRequest(Object(craft\\web\\Request))","#17 /container/application/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))","#18 /container/application/public/index.php(12): yii\\base\\Application->run()","#19 {main}"],"memory":4968520,"exception":"[object] (yii\\base\\ErrorException(code: 2): Undefined array key \"enabled\" at /container/application/vendor/verbb/image-resizer/src/services/Service.php:67)"}

### Steps to reproduce

1. 
2. 

### Craft CMS version

4.4.5

### Plugin version

3.0.x

### Multi-site?

Yes

**Comment by engram-design** [comment]
Should be fixed in [3.0.5](https://github.com/verbb/image-resizer/releases/tag/3.0.5), but let me know if not!
