### ISSUE TITLE
Image Resizer 3.0.5 not working on Craft 4.4.9

### ISSUE THREAD

**Issue by glenwith1n** [engram-design/ImageResizer#75]
### Describe the bug

After I updated Image Resizer to 3.0.5 I can no longer upload any images etc, the latest release has an issue - see error
verbb\imageresizer\services\Resize::_resizeImage(): Argument #2 ($width) must be of type ?int, string given, called in /home/webdev/www/vhosts/craft4/craft/vendor/verbb/image-resizer/src/services/Resize.php on line 99

### Steps to reproduce

1. 
2. 

### Craft CMS version

4.4.9

### Plugin version

3.0.5

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed in [3.0.6](https://github.com/verbb/image-resizer/releases/tag/3.0.6)
