### ISSUE TITLE
Uncaught TypeError `ResizeElementAction`

### ISSUE THREAD

**Issue by baileydoestech** [engram-design/ImageResizer#77]
### Describe the bug

We are seeing an issue on the assets view of the CP where JS for the plugin fails to load (as shown in the screenshot). When selecting the resize asset menu item nothing happens the first time but, weirdly, this is fine the second time. This is reproducible across environments (local DDEV and AWS EKS) - we host the CP on a different domain to the main site (multi-site setup) but have the correct access control headers in place (or none of the CP works). 
 
![jqueryerror](https://github.com/verbb/image-resizer/assets/3185073/de3883d4-8fbc-4049-b17d-4a3ed8636c1e)

### Steps to reproduce

1. Install latest image resizer plugin and activate
2. Go to the assets page in CP (see console error)
3. Try to resize an image (nothing happens)
4. Try again and the dialog box appears as expected

### Craft CMS version

Craft Pro 4.4.17

### Plugin version

3.0.6

### Multi-site?

Yes

**Comment by engram-design** [comment]
This seems to be caused by how JS is loaded as a bit of a race condition. It's basically loading the `new Craft.ImageResizer.ResizeElementAction()` call before the `image-resizer.js` file has loaded. It's not something I can reproduce reliably though and probably comes down to some strange behaviour with load order.

In fact, my testing shows that JS in the [`getTriggerHtml`](https://github.com/verbb/image-resizer/blob/cbab574b861ff008d2d0295edbed7b93338ad0c3/src/elementactions/ResizeImage.php#L37) isn't called until you select an asset (which makes the actions menu appear).

You can confirm if there's different behaviour on your end by modifying that file from:

```php
Craft::$app->getView()->registerJs('new Craft.ImageResizer.ResizeElementAction(' .
    '"' . $imageWidth . '", ' .
    '"' . $imageHeight . '", '
    . $type .
    ');');
```

```php
Craft::$app->getView()->registerJs('console.log("image-resizer"); new Craft.ImageResizer.ResizeElementAction(' .
    '"' . $imageWidth . '", ' .
    '"' . $imageHeight . '", '
    . $type .
    ');');
```

Then, try loading the assets index to see what happens. If you see the  console log notice in dev tools when you load the page, I'd be interested to know if you might have some other plugins changing behaviour.

**Comment by baileydoestech** [comment]
I do not see the console message when loading the assets index, can conform you are correct about the JS loading only when selecting an asset, these two files load as the error appears

![image](https://github.com/verbb/image-resizer/assets/3185073/43f3794a-a4cb-4248-8f73-35cb56985f4d)

Only because it caused some initial JS issues but could it be related to multi site setup? We have our CP on a different subdomain to the main site. However not seeing any other JS errors from Craft or other plugins we use

**Comment by engram-design** [comment]
I don’t _think_ it’d be your multi site setup, but just trying to figure out some ways to replicate things.

Would you be able to send through a screenshot of the water flow diagram for the network request? I’m just wondering if there’s something different to how files are loaded, or their order.

**Comment by baileydoestech** [comment]
Apologies for the delay, here you go. The last two items (`verbb-ui.js` and `image-resizer.js` load once selecting an asset) 
![image](https://github.com/verbb/image-resizer/assets/3185073/7e86028c-3090-448f-82b5-536fbcf65b5f)

**Comment by engram-design** [comment]
Thanks, seems pretty much what I would expect. I'll keep at trying to reproduce this one.

**Comment by baileydoestech** [comment]
FGO I think we are seeing a similar issue with Craft CMS JavaScript when trying to create new matrix blocks - similar behaviour which resolves after clicking around a few places. This is easily reproducible with a clean DDEV install and placing the control panel on its own domain. 

So my assumption is that is the issue (or multi site)

**Comment by engram-design** [comment]
Hmm, wondering if you might be able to share a repo of your DDEV install, just to see if I can replicate?

**Comment by baileydoestech** [comment]
https://github.com/baileydoestech/test-craft

Similar issue raised in the main Craft repo as we see other strikingly similar errors

**Comment by engram-design** [comment]
Yeah, lots of JS issues all around. I'll take a look!

**Comment by baileydoestech** [comment]
Resolved in https://github.com/craftcms/cms/issues/13628
