### ISSUE TITLE
"Skip larger resulting images" not working correctly

### ISSUE THREAD

**Issue by turnstylerj** [engram-design/ImageResizer#82]
### Describe the bug

I just installed and tested Image Resizer on our Craft 4 project, and it appears the option to skip larger resulting images isn't working correctly. I tested this with a 1.1MB image and the logs say it saved file size (and it did resize the asset) but the resulting image downloaded from the CMS is 2.2MB.

### Settings/Logs
![2023-12-13 at 14 15 27](https://github.com/verbb/image-resizer/assets/42223501/452d2a16-c577-47b1-9417-daa25fc6da54)
![2023-12-13 at 14 18 17](https://github.com/verbb/image-resizer/assets/42223501/6b39111c-b10c-4dbb-b18b-3cbbb81d1000)

### Before
![mono-log-ls1-GTFNwcM-unsplash](https://github.com/verbb/image-resizer/assets/42223501/8c272f3c-09b3-48c9-9607-ee459373e486)

### After
![mono-log-ls1-GTFNwcM-unsplash(1)](https://github.com/verbb/image-resizer/assets/42223501/61007f35-afb1-4bc8-a320-2ea89901b257)

### Steps to reproduce

1. Configure Image Resizer with above pictured settings
2. Upload attached "Before" image

### Craft CMS version

 4.5.11.1

### Plugin version

3.0.8

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed in [3.0.9](https://github.com/verbb/image-resizer/releases/tag/3.0.9)
