### ISSUE TITLE
Errors when resizing images on remote volumes within a subfolder

### ISSUE THREAD

**Issue by mattgrayisok** [engram-design/ImageResizer#83]
### Describe the bug

Hey! Should be a quick one. When a remote file is downloaded here:

https://github.com/verbb/image-resizer/blob/c87abfb24dcf5f11cf7fcdd3d0b48c59aca29815/src/services/Resize.php#L51

Currently only the asset's filename is being passed into the download function rather then the assets complete path. This results in an error when the asset is within a subfolder in a Volume.

E.G

For an asset inside a volume with subfolder `images/` and with a path of `news/2024//Liberation-SocialShare.jpg` only `Liberation-SocialShare.jpg` is being passed into the download function, resulting in:

`Error executing "GetObject" on "https://s3.eu-central-1.wasabisys.com/servd-ejcnet-net/staging/images/Liberation-SocialShare.jpg";`

Recommend changing `$filename` on Resize.phpL51 to `$asset->path` or `getPath()` or whatever.

🎉

### Steps to reproduce

1. Use remote FS
2. Have an image in a subfolder
3. Do anything that attempts to resize it

### Craft CMS version

4

### Plugin version

3.0.9

**Comment by engram-design** [comment]
Good call Matt, should be fixed in [3.0.10](https://github.com/verbb/image-resizer/releases/tag/3.0.10)

**Comment by mattgrayisok** [comment]
Thank you sir. Have informed the impacted client.
